language: go
go:
  - 1.3

install:
  - go get code.google.com/p/go.tools/cmd/cover
  - go get github.com/mattn/goveralls
  - make dependencies
  - make install

script:
  - make test
  - go test -race -v -covermode=count -coverprofile=coverage.out
  - $(go env GOPATH | awk 'BEGIN{FS=":"} {print $1}')/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

env:
  secure: "CPuDl59GuLvd8BFbJwuy2mynpN4e9l2LAPF42yaf8b9HQIYQPrSeycqQAIDPQgKhk4x3/FbX1JrvieTP/P2hx+alxJv6tvEvh/aGg91h/dgLpUHiIvBQfa7viUKZrxkER3pQg30Ql2fMJOz8gKPWyB0mNvm5Eh4ysdjJmILTGuM="
